### Warren Buffett’s Financial Statement Rules of Thumb

**UI Suggestions:**
- Build a UI that includes two key components (1) a chat-bot responds to user's questions with Warren Buffett investment insights (2) a dashboard to display the income statement, the balance sheet and the cashflow statement
- Allow users to change the stock symbol and review the financials of any publically traded firms
- Use my cacluation below as the starting point, add a function to your UI to calculate and display all the Warrent Buffetts' key financial ratios with the corresponding reference values (e.g., Gross Margin > 40%) for any user-input stock.
- Ideally, you could include some high-level introduction and interpretation of the above financial ratios or stock selection insights into the question-answer pairs for your Chat-Bot.

#### Reference: 
- https://tradingcenter.org/index.php/train/financial-ratios/380-warren-buffett-stock-trading-indicators
- https://www.investinassets.net/p/8-metrics-warren-buffett-use-to-identify-e96

#### INCOME STATEMENT:
1: Gross Margin
- Equation: Gross Profit / Revenue
- Rule: 40% or higher
- Buffett's Logic: Signals the company isn’t competing on price.

2: Selling General And Administration (SG & A Expense) Margin
- Equation: SG & A Expense / Gross Profit
- e.g. Selling General and Administration / Gross Profit
- Rule: 30% or lower
- Buffett's Logic: Wide-moat companies don’t need to spend a lot on overhead to operate.

3: Research And Development	(R & D Expense) Margin
- Equation: R & D Expense / Gross Profit
- e.g. Research And Development / Gross Profit
- Rule: 30% or lower
- Buffett's Logic: R&D expenses don't always create value for shareholders. 

4: Depreciation Margin
- Equation: Depreciation / Gross Profit
- e.g. Reconciled Depreciation / Gross Profit
- Rule: 10% or lower
- Buffett's Logic: Buffett doesn't like businesses that need to invest in depreciating assets to maintain their competitive advantage.

5: Interest Expense Margin
- Equation: Interest Expense / Operating Income
- Rule: 15% or lower
- Buffett's Logic: Great businesses don’t need debt to finance themselves.

6: Income Tax Expenses
- Equation: Tax Paid / Pre-Tax Income
- Tax Provision / Pre-Tax Income
- Rule: Current Corporate Tax Rate
- Buffett's Logic: Great businesses are so profitable that they are forced to pay their full tax load.

7: Net Margin (Profit Margin)
- Equation: Net Income / Sales
- e.g. Net Income / Total Revenue
- Rule: 20% or higher
- Buffett's Logic: Great companies convert 20% or more of their revenue into net income.

8: Earnings Per Share Growth
- Equation: Year 2 EPS / Year 1 EPS
- e.g. 09/30/2024 Basic EPS / 09/30/2023 Basic EPS
- Rule: Positive & Growing
- Buffett's Logic: Great companies increase profits every year.

In [ ]:
import pandas as pd
import numpy as np
import yfinance as yf

# Specify the stock you want to analyze (e.g., Medco)
stock_symbol = 'TSLA'
stocks = yf.Ticker('TSLA')
print(f'{stock_symbol}: FINANCIAL STATEMENT')
stocks.financials

AAPL: FINANCIAL STATEMENT

,2024-09-30,2023-09-30,2022-09-30,2021-09-30,2020-09-30
Tax Effect Of Unusual Items,0.0,0.0,0.0,0.0,NaN
Tax Rate For Calcs,0.241,0.147,0.162,0.133,NaN
Normalized EBITDA,134661000000.0,125820000000.0,130541000000.0,123136000000.0,NaN
Net Income From Continuing Operation Net Minority Interest,93736000000.0,96995000000.0,99803000000.0,94680000000.0,NaN
Reconciled Depreciation,11445000000.0,11519000000.0,11104000000.0,11284000000.0,NaN
Reconciled Cost Of Revenue,210352000000.0,214137000000.0,223546000000.0,212981000000.0,NaN
EBITDA,134661000000.0,125820000000.0,130541000000.0,123136000000.0,NaN
EBIT,123216000000.0,114301000000.0,119437000000.0,111852000000.0,NaN
Net Interest Income,NaN,-183000000.0,-106000000.0,198000000.0,890000000.0
Interest Expense,NaN,3933000000.0,2931000000.0,2645000000.0,2873000000.0
Interest Income,NaN,3750000000.0,2825000000.0,2843000000.0,3763000000.0
Normalized Income,93736000000.0,96995000000.0,99803000000.0,94680000000.0,NaN
Net Income From Continuing And Discontinued Operation,93736000000.0,96995000000.0,99803000000.0,94680000000.0,NaN
Total Expenses,267819000000.0,268984000000.0,274891000000.0,256868000000.0,NaN
Total Operating Income As Reported,123216000000.0,114301000000.0,119437000000.0,108949000000.0,NaN
Diluted Average Shares,15408095000.0,15812547000.0,16325819000.0,16864919000.0,NaN
Basic Average Shares,15343783000.0,15744231000.0,16215963000.0,16701272000.0,NaN
Diluted EPS,6.08,6.13,6.11,5.61,NaN
Basic EPS,6.11,6.16,6.15,5.67,NaN
Diluted NI Availto Com Stockholders,93736000000.0,96995000000.0,99803000000.0,94680000000.0,NaN
Net Income Common Stockholders,93736000000.0,96995000000.0,99803000000.0,94680000000.0,NaN
Net Income,93736000000.0,96995000000.0,99803000000.0,94680000000.0,NaN
Net Income Including Noncontrolling Interests,93736000000.0,96995000000.0,99803000000.0,94680000000.0,NaN
Net Income Continuous Operations,93736000000.0,96995000000.0,99803000000.0,94680000000.0,NaN
Tax Provision,29749000000.0,16741000000.0,19300000000.0,14527000000.0,NaN
Pretax Income,123485000000.0,113736000000.0,119103000000.0,109207000000.0,NaN
Other Income Expense,269000000.0,-565000000.0,-334000000.0,60000000.0,NaN
Other Non Operating Income Expenses,269000000.0,-565000000.0,-334000000.0,60000000.0,NaN
Net Non Operating Interest Income Expense,NaN,-183000000.0,-106000000.0,198000000.0,890000000.0
Interest Expense Non Operating,NaN,3933000000.0,2931000000.0,2645000000.0,2873000000.0
Interest Income Non Operating,NaN,3750000000.0,2825000000.0,2843000000.0,3763000000.0
Operating Income,123216000000.0,114301000000.0,119437000000.0,108949000000.0,NaN
Operating Expense,57467000000.0,54847000000.0,51345000000.0,43887000000.0,NaN
Research And Development,31370000000.0,29915000000.0,26251000000.0,21914000000.0,NaN
Selling General And Administration,26097000000.0,24932000000.0,25094000000.0,21973000000.0,NaN
Gross Profit,180683000000.0,169148000000.0,170782000000.0,152836000000.0,NaN
Cost Of Revenue,210352000000.0,214137000000.0,223546000000.0,212981000000.0,NaN
Total Revenue,391035000000.0,383285000000.0,394328000000.0,365817000000.0,NaN
Operating Revenue,391035000000.0,383285000000.0,394328000000.0,365817000000.0,NaN

In [ ]:
# Compute the ratios
financial_statement_readings = pd.DataFrame({
    'Gross Margin': stocks.financials.loc['Gross Profit'] / stocks.financials.loc['Total Revenue'], # 40% or higher
    'SG & A Expense Margin': stocks.financials.loc['Selling General And Administration'] / stocks.financials.loc['Gross Profit'], # 30% or lower
    'R & D Expense Margin': stocks.financials.loc['Research And Development'] / stocks.financials.loc['Gross Profit'], # 30% or lower
    'Depreciation Margin': stocks.financials.loc['Reconciled Depreciation'] / stocks.financials.loc['Gross Profit'], # 10% or lower
    'Interest Expense Margin': stocks.financials.loc['Interest Expense'] / stocks.financials.loc['Operating Income'],# 15% or lower
    'Income Tax Expense': stocks.financials.loc['Tax Provision'] / stocks.financials.loc['Pretax Income'], # Current Corporate Tax Rate
    'Profit Margin': stocks.financials.loc['Net Income'] / stocks.financials.loc['Total Revenue'], # 20% or higher
    'Earnings Per Share Growth': [stocks.financials.loc['Basic EPS', '2024-09-30'] / stocks.financials.loc['Basic EPS', '2023-09-30'], 
                                  stocks.financials.loc['Basic EPS', '2023-09-30'] / stocks.financials.loc['Basic EPS', '2022-09-30'], 
                                  stocks.financials.loc['Basic EPS', '2022-09-30'] / stocks.financials.loc['Basic EPS', '2021-09-30'],
                                  np.nan, np.nan] # > 1 Positive & Growing
}).T
print(financial_statement_readings)

                          2024-09-30 2023-09-30 2022-09-30 2021-09-30  \
Gross Margin                0.462063   0.441311   0.433096   0.417794
SG & A Expense Margin       0.144435   0.147398   0.146936   0.143768
R & D Expense Margin        0.173619   0.176857   0.153711   0.143382
Depreciation Margin         0.063343     0.0681   0.065019   0.073831
Interest Expense Margin          NaN   0.034409    0.02454   0.024277
Income Tax Expense          0.240912   0.147192   0.162045   0.133023
Profit Margin               0.239713   0.253062   0.253096   0.258818
Earnings Per Share Growth   0.991883   1.001626   1.084656        NaN

                          2020-09-30
Gross Margin                     NaN
SG & A Expense Margin            NaN
R & D Expense Margin             NaN
Depreciation Margin              NaN
Interest Expense Margin          NaN
Income Tax Expense               NaN
Profit Margin                    NaN
Earnings Per Share Growth        NaN

#### BALANCE SHEET:
9: Cash & Debt
- Equation:  Cash > Debt
- e.g. Cash And Cash Equivalents / Current Debt
- Rule: More cash than debt
- Buffett's Logic: Great companies generate lots of cash without needing much debt. 

11: Adjusted Debt to Equity
- Equation:  Total Liabilities / Shareholder Equity + Treasury Stock
- Total Shareholder Equity is the residual value of assets after deducting total liabilities. It includes common stock, retained earnings, and additional paid-in capital. 
- e.g. Total Debt / (Total Asset - Total Debt)
- Rule : < 0.80
- Buffett's Logic: Great companies finance themselves with equity. 

12: Preferred Stock
- Rule: None
- Buffett's Logic: Great companies don't need to fund themselves with preferred stock. 

13: Retained Earnings
- Equation:  Year 1 / Year 2
- Rule:  Consistent growth
- Buffett's Logic: Great companies grow retained earnings each year. 

14: Treasury Stock
- Rule: Exists
- Buffett's Logic: Great companies repurchase their stock.

In [ ]:
print(f'{stock_symbol}: BALANCE SHEET')
pd.set_option('display.max_rows', None)
stocks.balancesheet

AAPL: BALANCE SHEET

,2024-09-30,2023-09-30,2022-09-30,2021-09-30,2020-09-30
Treasury Shares Number,NaN,0.0,NaN,NaN,NaN
Ordinary Shares Number,15116786000.0,15550061000.0,15943425000.0,16426786000.0,NaN
Share Issued,15116786000.0,15550061000.0,15943425000.0,16426786000.0,NaN
Net Debt,76686000000.0,81123000000.0,96423000000.0,89779000000.0,NaN
Total Debt,106629000000.0,111088000000.0,132480000000.0,136522000000.0,NaN
Tangible Book Value,56950000000.0,62146000000.0,50672000000.0,63090000000.0,NaN
Invested Capital,163579000000.0,173234000000.0,170741000000.0,187809000000.0,NaN
Working Capital,-23405000000.0,-1742000000.0,-18577000000.0,9355000000.0,NaN
Net Tangible Assets,56950000000.0,62146000000.0,50672000000.0,63090000000.0,NaN
Capital Lease Obligations,NaN,12842000000.0,12411000000.0,11803000000.0,9842000000.0
Common Stock Equity,56950000000.0,62146000000.0,50672000000.0,63090000000.0,NaN
Total Capitalization,142700000000.0,157427000000.0,149631000000.0,172196000000.0,NaN
Total Equity Gross Minority Interest,56950000000.0,62146000000.0,50672000000.0,63090000000.0,NaN
Stockholders Equity,56950000000.0,62146000000.0,50672000000.0,63090000000.0,NaN
Gains Losses Not Affecting Retained Earnings,-7172000000.0,-11452000000.0,-11109000000.0,163000000.0,NaN
Other Equity Adjustments,-7172000000.0,-11452000000.0,-11109000000.0,163000000.0,NaN
Retained Earnings,-19154000000.0,-214000000.0,-3068000000.0,5562000000.0,NaN
Capital Stock,83276000000.0,73812000000.0,64849000000.0,57365000000.0,NaN
Common Stock,83276000000.0,73812000000.0,64849000000.0,57365000000.0,NaN
Total Liabilities Net Minority Interest,308030000000.0,290437000000.0,302083000000.0,287912000000.0,NaN
Total Non Current Liabilities Net Minority Interest,131638000000.0,145129000000.0,148101000000.0,162431000000.0,NaN
Other Non Current Liabilities,36634000000.0,34391000000.0,21737000000.0,18361000000.0,NaN
Tradeand Other Payables Non Current,9254000000.0,15457000000.0,16657000000.0,24689000000.0,NaN
Long Term Debt And Capital Lease Obligation,85750000000.0,95281000000.0,109707000000.0,119381000000.0,NaN
Long Term Capital Lease Obligation,NaN,11267000000.0,10748000000.0,10275000000.0,8382000000.0
Long Term Debt,85750000000.0,95281000000.0,98959000000.0,109106000000.0,NaN
Current Liabilities,176392000000.0,145308000000.0,153982000000.0,125481000000.0,NaN
Other Current Liabilities,51703000000.0,50010000000.0,52630000000.0,45965000000.0,NaN
Current Deferred Liabilities,8249000000.0,8061000000.0,7912000000.0,7612000000.0,NaN
Current Deferred Revenue,8249000000.0,8061000000.0,7912000000.0,7612000000.0,NaN
Current Debt And Capital Lease Obligation,20879000000.0,15807000000.0,22773000000.0,17141000000.0,NaN
Current Capital Lease Obligation,NaN,1575000000.0,1663000000.0,1528000000.0,1460000000.0
Current Debt,20879000000.0,15807000000.0,21110000000.0,15613000000.0,NaN
Other Current Borrowings,10912000000.0,9822000000.0,11128000000.0,9613000000.0,NaN
Commercial Paper,9967000000.0,5985000000.0,9982000000.0,6000000000.0,NaN
Payables And Accrued Expenses,95561000000.0,71430000000.0,70667000000.0,54763000000.0,NaN
Payables,95561000000.0,71430000000.0,70667000000.0,54763000000.0,NaN
Total Tax Payable,26601000000.0,8819000000.0,6552000000.0,NaN,NaN
Income Tax Payable,26601000000.0,8819000000.0,6552000000.0,NaN,NaN
Accounts Payable,68960000000.0,62611000000.0,64115000000.0,54763000000.0,NaN
Total Assets,364980000000.0,352583000000.0,352755000000.0,351002000000.0,NaN
Total Non Current Assets,211993000000.0,209017000000.0,217350000000.0,216166000000.0,NaN
Other Non Current Assets,55335000000.0,46906000000.0,39053000000.0,38762000000.0,NaN
Non Current Deferred Assets,19499000000.0,17852000000.0,15375000000.0,NaN,NaN
Non Current Deferred Taxes Assets,19499000000.0,17852000000.0,15375000000.0,NaN,NaN
Investments And Advances,91479000000.0,100544000000.0,120805000000.0,127877000000.0,NaN
Other Investments,NaN,NaN,120805000000.0,127877000000.0,100887000000.0
Investmentin Financial Assets,91479000000.0,100544000000.0,120805000000.0,127877000000.0,NaN
Available For Sale Securities,91479000000.0,100544000000.0,120805000000.0,127877000000.0,NaN
Net PPE,45680000000.0,43715000000.0,42117000000.0,49527000000.0,NaN
Accumulated Depreciation,-73448000000.0,-70884000000.0,-72340000000.0,-70283000000.0,NaN
Gross PPE,119128000000.0,114599000000.0,114457000000.0,119810000000.0,NaN
Leases,14233000000.0,12839000000.0,11271000000.0,11023000000.0,NaN
Other Properties,NaN,10661000000.0,10417000000.0,10087000000.0,8570000000.0
Machinery Furniture Equipment,80205000000.0,78314000000.0,81060000000.0,78659000000.0,NaN
Land And Improvements,24690000000.0,23446000000.0,22126000000.0,20041000000.0,NaN
Properties,0.0,0.0,0.0,0.0,NaN
Current Assets,152987000000.0,143566000000.0,135405000000.0,134836000000.0,NaN
Other Current Assets,14287000000.0,14695000000.0,21223000000.0,14111000000.0,NaN
Inventory,7286000000.0,6331000000.0,4946000000.0,6580000000.0,NaN
Receivables,66243000000.0,60985000000.0,60932000000.0,51506000000.0,NaN
Other Receivables,32833000000.0,31477000000.0,32748000000.0,25228000000.0,NaN
Accounts Receivable,33410000000.0,29508000000.0,28184000000.0,26278000000.0,NaN
Cash Cash Equivalents And Short Term Investments,65171000000.0,61555000000.0,48304000000.0,62639000000.0,NaN
Other Short Term Investments,35228000000.0,31590000000.0,24658000000.0,27699000000.0,NaN
Cash And Cash Equivalents,29943000000.0,29965000000.0,23646000000.0,34940000000.0,NaN
Cash Equivalents,2744000000.0,1606000000.0,5100000000.0,17635000000.0,NaN
Cash Financial,27199000000.0,28359000000.0,18546000000.0,17305000000.0,NaN

In [ ]:
# Compute the ratios
balance_sheet_readings = pd.DataFrame({
    'Cash > Debt': stocks.balancesheet.loc['Cash And Cash Equivalents'] / stocks.balancesheet.loc['Current Debt'], # Rule: cash > debt
    'Adjusted Debt to Equity': stocks.balancesheet.loc['Total Debt'] / (stocks.balancesheet.loc['Total Assets'] - stocks.balancesheet.loc['Total Debt']) # Rule : < 0.80
}).T
print(balance_sheet_readings)

                        2024-09-30 2023-09-30 2022-09-30 2021-09-30 2020-09-30
Cash > Debt                1.43412   1.895679   1.120133   2.237879        NaN
Adjusted Debt to Equity   0.412729   0.460001    0.60143   0.636526        NaN

#### CASH FLOW STATEMENT:
15: Capital Expenditures (CapEx) Margin
- Equation:  CapEx / Net Income
- e.g., Capital expenditures / Net Income From Continuing Operations
- Rule: <25%
- Buffett's Logic: Great companies don't need much equipment to generate profits.

In [ ]:
print(f'{stock_symbol}: CASHFLOW STATEMENT')
stocks.cashflow

AAPL: CASHFLOW STATEMENT

,2024-09-30,2023-09-30,2022-09-30,2021-09-30,2020-09-30
Free Cash Flow,108807000000.0,99584000000.0,111443000000.0,92953000000.0,NaN
Repurchase Of Capital Stock,-94949000000.0,-77550000000.0,-89402000000.0,-85971000000.0,NaN
Repayment Of Debt,-9958000000.0,-11151000000.0,-9543000000.0,-8750000000.0,NaN
Issuance Of Debt,0.0,5228000000.0,5465000000.0,20393000000.0,NaN
Issuance Of Capital Stock,NaN,NaN,NaN,1105000000.0,880000000.0
Capital Expenditure,-9447000000.0,-10959000000.0,-10708000000.0,-11085000000.0,NaN
Interest Paid Supplemental Data,NaN,3803000000.0,2865000000.0,2687000000.0,3002000000.0
Income Tax Paid Supplemental Data,26102000000.0,18679000000.0,19573000000.0,25385000000.0,NaN
End Cash Position,29943000000.0,30737000000.0,24977000000.0,35929000000.0,NaN
Beginning Cash Position,30737000000.0,24977000000.0,35929000000.0,39789000000.0,NaN
Changes In Cash,-794000000.0,5760000000.0,-10952000000.0,-3860000000.0,NaN
Financing Cash Flow,-121983000000.0,-108488000000.0,-110749000000.0,-93353000000.0,NaN
Cash Flow From Continuing Financing Activities,-121983000000.0,-108488000000.0,-110749000000.0,-93353000000.0,NaN
Net Other Financing Charges,-5802000000.0,-6012000000.0,-6383000000.0,-5580000000.0,NaN
Cash Dividends Paid,-15234000000.0,-15025000000.0,-14841000000.0,-14467000000.0,NaN
Common Stock Dividend Paid,-15234000000.0,-15025000000.0,-14841000000.0,-14467000000.0,NaN
Net Common Stock Issuance,-94949000000.0,-77550000000.0,-89402000000.0,-85971000000.0,NaN
Common Stock Payments,-94949000000.0,-77550000000.0,-89402000000.0,-85971000000.0,NaN
Common Stock Issuance,NaN,NaN,NaN,1105000000.0,880000000.0
Net Issuance Payments Of Debt,-5998000000.0,-9901000000.0,-123000000.0,12665000000.0,NaN
Net Short Term Debt Issuance,3960000000.0,-3978000000.0,3955000000.0,1022000000.0,NaN
Net Long Term Debt Issuance,-9958000000.0,-5923000000.0,-4078000000.0,11643000000.0,NaN
Long Term Debt Payments,-9958000000.0,-11151000000.0,-9543000000.0,-8750000000.0,NaN
Long Term Debt Issuance,0.0,5228000000.0,5465000000.0,20393000000.0,NaN
Investing Cash Flow,2935000000.0,3705000000.0,-22354000000.0,-14545000000.0,NaN
Cash Flow From Continuing Investing Activities,2935000000.0,3705000000.0,-22354000000.0,-14545000000.0,NaN
Net Other Investing Changes,-1308000000.0,-1337000000.0,-2086000000.0,-385000000.0,NaN
Net Investment Purchase And Sale,13690000000.0,16001000000.0,-9560000000.0,-3075000000.0,NaN
Sale Of Investment,62346000000.0,45514000000.0,67363000000.0,106483000000.0,NaN
Purchase Of Investment,-48656000000.0,-29513000000.0,-76923000000.0,-109558000000.0,NaN
Net Business Purchase And Sale,NaN,NaN,-306000000.0,-33000000.0,-1524000000.0
Purchase Of Business,NaN,NaN,-306000000.0,-33000000.0,-1524000000.0
Net PPE Purchase And Sale,-9447000000.0,-10959000000.0,-10708000000.0,-11085000000.0,NaN
Purchase Of PPE,-9447000000.0,-10959000000.0,-10708000000.0,-11085000000.0,NaN
Operating Cash Flow,118254000000.0,110543000000.0,122151000000.0,104038000000.0,NaN
Cash Flow From Continuing Operating Activities,118254000000.0,110543000000.0,122151000000.0,104038000000.0,NaN
Change In Working Capital,3651000000.0,-6577000000.0,1200000000.0,-4911000000.0,NaN
Change In Other Working Capital,NaN,NaN,478000000.0,1676000000.0,2081000000.0
Change In Other Current Liabilities,15552000000.0,3031000000.0,6110000000.0,7475000000.0,NaN
Change In Other Current Assets,-11731000000.0,-5684000000.0,-6499000000.0,-8042000000.0,NaN
Change In Payables And Accrued Expense,6020000000.0,-1889000000.0,9448000000.0,12326000000.0,NaN
Change In Payable,6020000000.0,-1889000000.0,9448000000.0,12326000000.0,NaN
Change In Account Payable,6020000000.0,-1889000000.0,9448000000.0,12326000000.0,NaN
Change In Inventory,-1046000000.0,-1618000000.0,1484000000.0,-2642000000.0,NaN
Change In Receivables,-5144000000.0,-417000000.0,-9343000000.0,-14028000000.0,NaN
Changes In Account Receivables,-3788000000.0,-1688000000.0,-1823000000.0,-10125000000.0,NaN
Other Non Cash Items,-2266000000.0,-2227000000.0,1006000000.0,-4921000000.0,NaN
Stock Based Compensation,11688000000.0,10833000000.0,9038000000.0,7906000000.0,NaN
Deferred Tax,NaN,NaN,895000000.0,-4774000000.0,-215000000.0
Deferred Income Tax,NaN,NaN,895000000.0,-4774000000.0,-215000000.0
Depreciation Amortization Depletion,11445000000.0,11519000000.0,11104000000.0,11284000000.0,NaN
Depreciation And Amortization,11445000000.0,11519000000.0,11104000000.0,11284000000.0,NaN
Net Income From Continuing Operations,93736000000.0,96995000000.0,99803000000.0,94680000000.0,NaN

In [ ]:
# Compute the ratios
cashflow_statement_readings = pd.DataFrame({
    'CapEx Margin': -stocks.cashflow.loc['Capital Expenditure'] / stocks.cashflow.loc['Net Income From Continuing Operations'], # Rule: <25%
}).T
print(cashflow_statement_readings)

             2024-09-30 2023-09-30 2022-09-30 2021-09-30 2020-09-30
CapEx Margin   0.100783   0.112985   0.107291   0.117079        NaN